import { Inter, Outfit } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.css'
import "./globals.css";

// Import the Inter and Outfit fonts
export const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});

export const outfit = Outfit({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* Add both font classes */}
      <body className={`${inter.className} ${outfit.className}`}>
        {children}
      </body>
    </html>
  );
}
